worker_processes  1;

events {
    worker_connections  1024;
}

http {
    resolver 127.0.0.11 valid=30s;
    resolver_timeout 5s;
    
    server {
        listen       3000;
        server_name  localhost;

        # Auth test login page
        location /test-page/ {
            proxy_pass http://host.docker.internal:4010/test-page/;
        }

        # Files (bento-files)
        location /api/files/ {
            #proxy_pass http://127.0.0.1:4000/api/files/;
            set $files_backend "dataservice-dev.datacommons.cancer.gov";
            proxy_pass https://$files_backend/api/files/;
            proxy_ssl_server_name on;
        }

        # Authentication (bento-auth)
        location /api/auth/ {
            #proxy_pass http://127.0.0.1:4010/api/auth/;
            set $auth_backend "dataservice-dev.datacommons.cancer.gov";
            proxy_pass https://$auth_backend/api/auth/;
            proxy_ssl_server_name on;
        }

        # Authorization (bento-users)
        location /api/users/ {
            #proxy_pass http://127.0.0.1:4020/api/users/;
            set $users_backend "dataservice-dev.datacommons.cancer.gov";
            proxy_pass https://$users_backend/api/users/;
            proxy_ssl_server_name on;
        }

        # Backend (metadata)
        location /v1/graphql/ {
            proxy_pass http://host.docker.internal:8080/v1/graphql/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # Backend Public(metadata)
        location /v1/public-graphql/ {
            proxy_pass http://host.docker.internal:8080/v1/graphql/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        # Interop (interop)
        location /api/interoperation/graphql/ {
            #CDS-DEV
            set $interop_backend "dataservice-dev2.datacommons.cancer.gov";
            proxy_pass https://$interop_backend/api/interoperation/graphql/;
            proxy_ssl_server_name on;
        }
        location /version/ {
            proxy_pass http://host.docker.internal:8080/version;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        # Frontend
        location / {
            proxy_pass http://host.docker.internal:3010/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
